---
- name: create symbolic link for environment variables
  ansible.builtin.copy:
      remote_src: true
      owner: test
      group: test
      mode: "0755"
      src: /home/test/.server_config_files/reactApp.env
      dest: /home/test/front_end/.env
