---
- name: Update and install base packages
  ansible.builtin.import_tasks: update_and_install_packages.yml
  tags: [packages]

- name: Install Neovim AppImage
  ansible.builtin.import_tasks: install_neovim_appimage.yml
  when: system_base_install_neovim | bool
  tags: [neovim]

- name: Configure hostname
  ansible.builtin.import_tasks: hostname.yml
  tags: [hostname]

- name: Configure static IP
  ansible.builtin.import_tasks: static_ip.yml
  when: system_base_manage_static_ip | bool
  tags: [ip, network]

- name: Set up Ansible testing tools
  ansible.builtin.import_tasks: setup_testing_tools.yml
  when: system_base_setup_testing_tools | bool
  tags: [testing]
