---
- name: Update packages on Debian/Ubuntu
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    autoremove: true
    autoclean: true
  register: system_base_update_result
  when:
    - ansible_os_family == "Debian"
    - system_base_upgrade_packages | bool
  notify: Reboot System

- name: Upgrade packages on RedHat/Fedora
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true
  register: system_base_update_result
  when:
    - ansible_os_family == "RedHat"
    - system_base_upgrade_packages | bool
  notify: Reboot System

- name: Merge and deduplicate package lists
  ansible.builtin.set_fact:
    system_base_packages_to_install: >-
      {{
        (
          host_system_packages | default([])
          +
          local_system_packages | default([])
        ) | unique | list
      }}

- name: Install base packages
  ansible.builtin.package:
    name: "{{ system_base_packages_to_install }}"
    state: "{{ system_base_package_state }}"
  when: system_base_packages_to_install | length > 0
