# ----------------------------------------
# Set system hostname and update /etc/hosts
# Only runs if 'hostname' is defined in host_vars
# ----------------------------------------

- name: Configure system hostname if defined
  block:
    - name: Set system hostname
      hostname:
        name: "{{ host_hostname }}"

    - name: Ensure hostname is listed in /etc/hosts (Debian-style)
      lineinfile:
        path: /etc/hosts
        regexp: '^127\\.0\\.1\\.1\\s+'
        line: "127.0.1.1 {{ host_hostname }}"
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Ensure hostname is listed in /etc/hosts (Non-Debian fallback)
      lineinfile:
        path: /etc/hosts
        regexp: '^127\\.0\\.0\\.1\\s+localhost'
        line: "127.0.0.1 localhost {{ host_hostname }}"
        state: present
      when: ansible_facts['os_family'] != "Debian"

  when: host_hostname is defined

  vars:
    host_hostname: "{{ hostname }}"
