- block:
    - name: Ensure keyring dir exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Check if Docker GPG key exists
      stat:
        path: /etc/apt/keyrings/docker.gpg
      register: docker_gpg

    - name: Add Docker GPG key if missing
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'
      when: not docker_gpg.stat.exists

    - name: Add Docker APT repo
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        filename: docker
        state: present

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes
      notify: Restart Docker

    - name: Install Docker Compose (Debian/RedHat)
      package:
        name: docker-compose
        state: latest
      when:
        - install_docker | bool
        - ansible_os_family in ["Debian", "RedHat"]

  when:
    - install_docker | bool
    - ansible_distribution == "Ubuntu"
