- name: Set the system hostname
  hostname:
    name: "{{ system_hostname }}"
  when: system_hostname is defined

- name: Ensure hostname is listed in /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: "^127\\.0\\.1\\.1\\s+"
    line: "127.0.1.1 {{ system_hostname }}"
  when: system_hostname is defined
