---
- name: Provisioning server for hosting application
  hosts: web_servers
  become: yes

  roles:
    - update_system
    - install_system_packages
    - configure_docker_on_ubuntu
    - configure_user
    - setup_fastapi
    # - setup_nodejs_api
    # - setup_react_app
