---
- name: Provisioning server for hosting application
  hosts: app
  become: yes

  roles:
    - update_and_upgrade_system
    - install_packages
    - docker_ubuntu_install
    - create_users_and_directories
    - create_server_symlinks
