---
- name: Updating and installing packages on development system
  hosts: devservers
  become: yes

  roles:
    - update_and_upgrade_system
    - install_packages
    - docker_ubuntu_install
    - create_users_and_directories
    - setup_fastAPI_repo
    - setup_nodejs_api_repo
    - setup_react_frontend_repo
    - configure_development_environment
