---
  - name: "Setting up local Linux machine"
    hosts: localhost
    connection: local 
    become: yes

    pre_tasks:
      - name: update and upgrade the system
        pacman:
          update_cache: yes
          upgrade: yes

