# Added task to create directories on local system
---
  - name: "Setting up local Linux machine"
    hosts: localhost
    connection: local 
    become: yes

    pre_tasks:
      - name: update and upgrade the system
        pacman:
          update_cache: yes
          upgrade: yes

    tasks:
      - name: Create a login user
        ansible.builtin.user:
          name: test
          # password: 'test'
          # groups: # Empty by default, here we give it some groups
          # - docker
          # - sudo
          state: present
          shell: /bin/bash       # Defaults to /bin/bash
          system: no             # Defaults to no
          createhome: yes        # Defaults to yes
          home: /home/test  # Defaults to /home/<username>

      - name: install applications for the system
        pacman:
          name: 
            - htop
            - mc
            - tmux
            - github-cli
            - xorg-server
            - xorg-xwininfo
            - xorg-xinit
            - ttf-linux-libertine
            - bc
            - xcompmgr
            - xorg-xprop
            - arandr
            - dosfstools
            - libnotify
            - dunst
            - exfat-utils
            - sxiv
            - xwallpaper
            - ffmpeg
            - gnome-keyring
            - neovim
            - mpd
            - mpc
            - mpv
            - man-db
            - ncmpcpp
            - newsboat
            - noto-fonts-emoji
            - ntfs-3g
            - pulsemixer
            - pamixer
            - maim
            - unclutter
            - unrar
            - unzip
            - lynx
            - xcape
            - xclip
            - xdotool
            - xorg-xdpyinfo
            - youtube-dl
            - zathura
            - zathura-pdf-mupdf
            - poppler
            - mediainfo
            - fzf
            - highlight
            - xorg-xbacklight
            - slock
            - socat
            - moreutils
            - docker
            - hostapd
            - python
            - python-pip
            - nodejs
            - gvim
            - yamllint
            - cmake
            - prettier
            - eslint
            # These are not available on arch
            # - atool
            # - abook
            # - sc-im

      # - name: Create home folders for the user
      - name: create Direcotories
        file:
          # path: /tmp/test 
          # state: directory
          path: /tmp/{{ item.path }} 
          mode: "{{ item.mode  }}"
          state: directory
        with_items:
          - { path: "test777", mode: "u=rwX,g=rwX,o=rwX" }
          - { path: "test755", mode: "u=rwX,g=rX,o=rX" }
          - { path: "test740", mode: "u=rwX,g=r" }
