---
  - name: "Setting up local Linux machine"
    hosts: localhost
    connection: local
    become: yes

    pre_tasks:
      - name: update and upgrade the system
        pacman:
          update_cache: yes
          upgrade: yes

    tasks:
      - name: Create a login user
        ansible.builtin.user:
          name: test
          password: 'test'
          - docker
          - sudo
          state: present
          shell: /bin/bash       # Defaults to /bin/bash
          system: no             # Defaults to no
          createhome: yes        # Defaults to yes
          home: /home/test  # Defaults to /home/<username>

      - name: install applications for the system
        pacman:
          name: 
            - htop
            - mc
            - tmux
            - github-cli
            - xorg-server
            - xorg-xwininfo
            - xorg-xinit
            - ttf-linux-libertine
            - bc
            - xcompmgr
            - xorg-xprop
            - arandr
            - dosfstools
