- name: Check if Docker is already installed
  command: docker --version
  register: docker_check
  failed_when: false
  changed_when: false

- name: Install or reinstall Docker on Ubuntu
  when:
    - install_docker | default(true) | bool
    - (docker_check.rc != 0) or (force_docker_reinstall | bool)
    - ansible_distribution == "Ubuntu"
  block:
    - name: Remove old Docker APT source (if present)
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    - name: Remove old Docker GPG key (if present)
      file:
        path: /etc/apt/keyrings/docker.gpg
        state: absent

    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Create Docker keyring directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Docker GPG key and dearmor
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Set permissions on Docker GPG key
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: "0644"

    - name: Add Docker APT repository
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu noble stable

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - docker-compose
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest

    - name: Ensure 'docker' group exists
      group:
        name: docker
        state: present

    - name: Add current Ansible-connected user to docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes
