- import_tasks: update_and_install_packages.yml
  tags: [packages]

- name: Install Neovim via AppImage
  import_tasks: install_neovim_appimage.yml
  tags: [neovim]

- import_tasks: install_docker.yml
  tags: [docker]

- import_tasks: hostname.yml
  tags: [hostname]

- import_tasks: static_ip.yml
  tags: [ip]

- import_tasks: configure_git.yml
  tags: [git]

- name: Ensure required system packages are installed
  ansible.builtin.package:
    name:
      - python3
      - python3-venv
      - python3-pip
    state: present
  become: true

- name: Create Python virtual environment
  ansible.builtin.command:
    cmd: python3 -m venv /opt/molecule-venv
    creates: /opt/molecule-venv/bin/activate

- name: Upgrade pip and tools inside venv
  ansible.builtin.command:
    cmd: /opt/molecule-venv/bin/pip install --upgrade pip setuptools wheel

- name: Install Ansible testing tools in venv
  ansible.builtin.pip:
    name:
      - ansible
      - molecule
      - testinfra
      - ansible-lint
      - yamllint
    virtualenv: /opt/molecule-venv
    virtualenv_command: python3 -m venv
