- name: Update packages (Debian)
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes
    autoclean: yes
  register: update_result
  when: ansible_os_family == "Debian"
  notify: Reboot System

- name: Upgrade packages (RedHat/Fedora)
  dnf:
    name: "*"
    state: latest
    update_cache: yes
  register: update_result
  when: ansible_os_family == "RedHat"
  notify: Reboot System

- name: Merge and deduplicate package lists
  set_fact:
    packages_to_install: "{{ host_system_packages | default([]) + local_system_packages | default([]) | unique }}"

- name: Install combined packages
  package:
    name: "{{ packages_to_install }}"
    state: latest
