---
- name: Install Docker Module for Python
  pip:
    name: docker

- name: Create docker containers
  community.docker.docker_image:
    name: "{{ container_name }}"
    image: "{{ container_image }}"
    command: "{{ container_command }}"
    state: present
  with_sequence: count={{ container_count }}

- name: Ensure destination directory exists
  file:
    path: "{{ repo.dest_path }}"
    state: directory

- name: Clone repository from GitHub
  git:
    repo: "{{ repo.url }}"
    dest: "{{ repo.dest_path }}/{{ repo.name }}"
    version: "{{ repo.version }}"
    update: yes
