---
- name: Clone {{ repo_name }} (version {{ tag }})
  ansible.builtin.git:
    repo: "{{ repo_url }}"
    dest: "/home/{{ git_user }}/{{ repo_name }}/"
    key_file: "/home/{{ git_user }}/.ssh/{{ repo_key }}"
    single_branch: yes
    force: yes
    version: "{{ tag }}"
    accept_hostkey: yes
  become_user: "{{ git_user }}"
