---
- name: Configure UFW firewall
  ansible.builtin.import_tasks: firewall_ufw.yml
  when: system_security_firewall_backend == "ufw"

- name: Configure firewalld firewall
  ansible.builtin.import_tasks: firewall_firewalld.yml
  when: system_security_firewall_backend == "firewalld"
