---
- name: Install security packages on Debian/Ubuntu
  ansible.builtin.apt:
    name: "{{ system_security_packages }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"
