# 192.168.1.90

ansible_host: 192.168.1.90

ansible_ssh_private_key_file: /home/m/.ssh/application_key

# system_hostname: host-laptop
#
# interface_name: wlp2s0
#
# interface_type: wifi
#
# static_ip: 192.168.0.52
