# === Ansible Connection Settings (host-specific) ===
ansible_host: 192.168.1.90
ansible_ssh_private_key_file: "{{ssh_key_dir}}/application_key"

# === Host-specific Networking Settings ===
interface_name: enp3s0
interface_type: ethernet

# === System Metadata ===
# system_hostname: host-laptop
static_ip: null
