---
- name: Validate system_host inputs
  ansible.builtin.import_tasks: validate.yml
  tags: [always]

- name: Install host packages
  ansible.builtin.import_tasks: packages.yml
  tags: [packages, host_packages]

- name: Create host directories
  ansible.builtin.import_tasks: directories.yml
  tags: [directories, apps]

- name: Configure Docker host
  ansible.builtin.import_tasks: docker.yml
  when: system_host_install_docker | bool
  tags: [docker]

- name: Configure host security services
  ansible.builtin.import_tasks: security.yml
  tags: [security]

- name: Configure firewall
  ansible.builtin.import_tasks: firewall.yml
  when: system_host_enable_firewall | bool
  tags: [firewall, security]
