---
- name: Synchronize WebAppServer database backup data with deveolopment system
  ansible.posix.synchronize:
    checksum: true
    mode: pull
    src: "{{ db_backup_source_directory }}"
    dest: "{{ db_backup_destination_directory }}"
  become: false

- name: Synchronize app control scripts with host
  ansible.posix.synchronize:
    checksum: true
    links: false
    delete: true
    src: "{{ scripts_source_directory }}"
    dest: "{{ scripts_destination_directory }}"
  become: false

- name: Synchronize application files with WebAppServer
  ansible.posix.synchronize:
    checksum: true
    links: false
    recursive: true
    delete: true
    src: "{{ config_files_source_directory }}"
    dest: "{{ config_files_destination_directory }}"
  become: false
