# DEVELOPMENT SYSTEM
[dev]
localhost

# DATABASE SERVER
[db]
192.168.1.26 ansible_ssh_private_key_file=/home/m/.ssh/ansible_rsa

# APPLICATION API SERVER
#[api]
#192.168.1.26 ansible_ssh_private_key_file=/home/m/.ssh/ansible_rsa

# APPLICATION FRONTEND SERVER
# [app]
#192.168.1.26 ansible_ssh_private_key_file=/home/m/.ssh/ansible_rsa

# GROUP OF MULTI WITH ALL SERVERS 
[app:children]
db
# app
# api
