---
all:
  children:
    # Common managed Linux systems
    systems:
      children:
        system_dev:
          hosts:
            local_system:

        server_hosts:
          hosts:
            aoife:
            laura:

        kiosk_hosts:
          hosts:
            kiosk_1:
            kiosk_2:
            kiosk_3:
            kiosk_4:
            kiosk_5:

    # Shared SSH/firewall/security layer
    secure_hosts:
      children:
        server_hosts:
        kiosk_hosts:

    # VFIO / GPU passthrough hosts
    vfio_hosts:
      hosts:
        dev_desktop:

    # Application deployment layers
    apps:
      children:
        frontend_service:
          hosts:
            laura:
            aoife:

        database_service:
          hosts:
            laura:
            aoife:

        file_service:
          hosts:
            laura:
            aoife:

        manufacturing_service:
          hosts:
            laura:
            aoife:

        pallet_service:
          hosts:
            laura:
            aoife:

        product_service:
          hosts:
            laura:
            aoife:

        label_service:
          hosts:
            laura:
            aoife:
