all:
  children:

    # host_systems:
    #   children:
        # frontend_reactapp
        # backend_labelapi
        # backend_palletapi

    local_systems:
      hosts:
        dev_system_local: {}

    # frontend:
    #   hosts:
    #     host2: {}
    #
    # backend_labelapi:
    #   hosts:
    #     host2: {}
    #
    # backend_palletapi:
    #   hosts:
    #     host2: {}
