---
all:
  children:
    # Common managed Linux machines
    managed_linux_hosts:
      children:
        dev_control_hosts:
          hosts:
            local_system:

        service_runtime_hosts:
          hosts:
            aoife:
            laura:

        kiosk_display_hosts:
          hosts:
            kiosk_1:
            kiosk_2:
            kiosk_3:
            kiosk_4:
            kiosk_5:

    # Shared SSH/firewall/security layer
    secured_linux_hosts:
      children:
        service_runtime_hosts:
        kiosk_display_hosts:

    # VFIO / GPU passthrough hosts
    vfio_hosts:
      hosts:
        dev_desktop:

    # Parent group for deployable service target groups
    service_deployment_targets:
      children:
        frontend_service:
          hosts:
            laura:
            aoife:

        database_service:
          hosts:
            laura:
            aoife:

        file_service:
          hosts:
            laura:
            aoife:

        manufacturing_service:
          hosts:
            laura:
            aoife:

        pallet_service:
          hosts:
            laura:
            aoife:

        product_service:
          hosts:
            laura:
            aoife:

        label_service:
          hosts:
            laura:
            aoife:
