# DEVELOPMENT SYSTEM
[control]
localhost ansible_connection=local ansible_user=root

# APPLICATION SERVER
[db_servers]
192.168.1.26 ansible_ssh_private_key_file=/home/m/.ssh/ansible_rsa

[all:children]
control
db_servers

# webservers
# server1 ansible_host=192.168.1.1 ansible_user=ubuntu
# server2 ansible_host=192.168.1.2 ansible_user=ubuntu

# [webservers:vars]
# nginx_port=80

# [dbservers:vars]
# db_user=root
# db_pass=password

