# DEVELOPMENT SYSTEM
[devservers]
localhost

[dbservers]
192.168.1.26 ansible_ssh_private_key_file=/home/m/.ssh/ansible_rsa

[webservers]
192.168.1.26 ansible_ssh_private_key_file=/home/m/.ssh/ansible_rsa

# [all]
# server1 ansible_host=192.168.1.1 ansible_user=ubuntu
# server2 ansible_host=192.168.1.2 ansible_user=ubuntu

# [webservers:vars]
# nginx_port=80

# [dbservers:vars]
# db_user=root
# db_pass=password

