- name: Sync application data
  delegate_to: "{{ rsync_source_host }}"
  synchronize:
    src: "{{ rsync_source_path }}"
    dest: "{{ rsync_dest_path }}"
    rsync_opts:
      - "--archive"
      - "--delete"
      - "--compress"
    mode: push
    ssh_args: "-o StrictHostKeyChecking=no"
  when: rsync_enabled
