---
- name: generate ansible ssh keypair
  community.crypto.openssh_keypair:
    path: "/home/{{ local_usr }}/.ssh/application"
    type: ed25519
    state: present
    size: 4096
  become: no

- name: generate github openssh keypAIR
  community.crypto.openssh_keypair:
    path: "/home/{{ local_usr }}/.ssh/github"
    type: ed25519
    state: present
    size: 4096
  become: no

- name: create the ssh config file
  template:
    src: "templates/ssh_config.j2"
    dest: "/home/{{ local_usr }}/.ssh/config"
    owner: "{{ local_usr }}"
  become: no

- name: evaluating the authentication agent & adding the key...
  shell: |
    eval "$(ssh-agent)"
    ssh-add /home/m/.ssh/github_key
    ssh-add /home/m/.ssh/application_key
  become: no
