---
- name: Updating installed packages
  ansible.builtin.package:
    update_cache: yes
    upgrade: yes

- name: Upgrade all packages
  apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes
