---
- name: "Creating user: {{ user }}"
  ansible.builtin.user:
    state: present
    name: "{{ user }}"
    create_home: yes
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: ".ssh/{{ user }}_rsa"
    groups:
    - docker
    - sudo

- name: "Creating directory for application data in {{ user }} home directory"
  file:
    path: "/home/{{ user }}/{{ item.path }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "{{ item.attrs }}"
    recurse: yes
  with_items:
    "{{ app_dirs }}"

- name: Configure SSH key
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', ssh_public_key_path) }}"

- name: Set up authorized SSH key
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ ssh_public_key }}"

