---
- name: Update to the latest version of Nodejs API
  ansible.builtin.git:
    repo: 'https://github.com/kfcodes/product_database_api.git'
    dest: /home/test/product_database_API/
    force: yes
    single_branch: yes
    version: removing_unused_routes

- name: Install npm packages for Nodejs API
  community.general.npm:
    path: /home/test/product_database_API/
    state: latest
