---
- name: Clone FastAPI repo
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.path }}"
    version: "{{ item.branch }}"
    update: yes
  loop: "{{ fastapi_apps }}"

- name: Copy .env file (optional)
  copy:
    src: "{{ item.env_file }}"
    dest: "{{ item.path }}/app/.env"
    remote_src: yes
  when: item.env_file is defined
  loop: "{{ fastapi_apps }}"

- name: Copy model files (optional)
  copy:
    src: "{{ item.models_src }}"
    dest: "{{ item.path }}/{{ item.models_dest }}"
    remote_src: yes
  when: item.models_src is defined and item.models_dest is defined
  loop: "{{ fastapi_apps }}"

- name: Template Docker Compose file
  template:
    src: docker-compose.yaml.j2
    dest: "{{ item.path }}/docker-compose.yml"
  loop: "{{ fastapi_apps }}"

- name: Ensure Docker network exists (nginx reverse proxy or app)
  docker_network:
    name: "{{ item.network }}"
    state: present
  when: item.network is defined
  loop: "{{ fastapi_apps }}"

- name: Stop existing container
  shell: docker container stop {{ item.name }}
  ignore_errors: true
  loop: "{{ fastapi_apps }}"

- name: Remove existing container
  shell: docker container rm {{ item.name }}
  ignore_errors: true
  loop: "{{ fastapi_apps }}"

- name: Build and start container with Docker Compose
  shell: docker compose up --build --detach
  args:
    chdir: "{{ item.path }}"
  loop: "{{ fastapi_apps }}"

- name: Connect container to Docker network (if defined)
  shell: docker network connect {{ item.network }} {{ item.name }}
  when: item.network is defined
  ignore_errors: true
  loop: "{{ fastapi_apps }}"
