---
- name: DOWNLOADING GIT REPOSITORY DATA {{ git_repo_name }} - {{ git_version }}
  ansible.builtin.git:
    repo: "{{ git_repo_url }}"
    dest: "/home/{{ git_user_name }}/{{ git_repo_name }}/"
    single_branch: yes
    force: yes
    version: "{{ git_version }}"
