- name: Check if GPU PCI IDs are already configured
  include_tasks: detect_gpu.yml
  when: gpu_bdf | length == 0 or gpu_pci_ids | length == 0
  tags: [detect]

- name: Proceed with full VFIO and passthrough configuration
  include_tasks: configure_gpu.yml
  when: gpu_bdf | length > 0 and gpu_pci_ids | length > 0
  tags: [setup]
