---

- name: Configure Cron job for regular DB backup
  ansible.builtin.cron:
    name: Backup DB every hour every hour
    special_time: hourly
    job: "/home/{{ scripts_directory }}/{{ regular_backup_script }}"
    state: present
  become: false

- name: Configure Cron job for semi-regular DB backup
  ansible.builtin.cron:
    name: Backup DB every day
    special_time: daily
    job: "/home/{{ scripts_directory }}/{{ semi_regular_backup_script }}"
    state: present
  become: false

