# Default options applied to each user unless overridden
default_user_options:
  state: present
  shell: /bin/bash
  create_home: true
  groups: users
  generate_ssh_key: false
  ssh_key_bits: 4096

# Controls whether SSH public keys are injected into users
enable_ssh_key_management: true

# SSH key generation settings
ssh_key_name: ansible
ssh_key_type: ed25519
ssh_key_bits: 4096
ssh_key_comment: "Ansible managed key"
ssh_key_dir: "{{ lookup('env','HOME') }}/.ssh"
ssh_key_private_path: "{{ ssh_key_dir }}/{{ ssh_key_name }}"
ssh_key_public_path: "{{ ssh_key_private_path }}.pub"
ssh_key_generate: false  # Set to true in host_vars or group_vars to enable key generation
