---
- name: Ensure React app git repo is present
  ansible.builtin.git:
    repo: 'https://github.com/kfcodes/production_documentation.git'
    dest: /home/test/front_end/
    version: new_api_routes
- name: Update React packages based on package.json to their latest version
  community.general.npm:
    path: /home/test/front_end/
    state: latest
