---
- name: "copying config files for {{ item.repo_name }}"
  ansible.builtin.copy:
    remote_src: yes
    src: "/home/{{ item.user_name }}/.application/server_config_files/reactApp.env"
    dest: "/home/{{ item.user_name }}/{{ item.repo_name }}/.env"
