---
- name: Ensure required packages are installed
  apt:
    name: "{{ base_packages + wm_packages + (['unclutter'] if enable_unclutter else []) + extra_packages }}"
    state: present
    update_cache: true
    install_recommends: "{{ apt_install_recommends }}"
  become: true

- name: Create systemd drop-in directory for agetty
  file:
    path: "/etc/systemd/system/getty@{{ autologin_tty }}.service.d"
    state: directory
    mode: "0755"
  become: true

- name: Configure agetty auto-login drop-in
  template:
    src: getty-override.conf.j2
    dest: "/etc/systemd/system/getty@{{ autologin_tty }}.service.d/override.conf"
    mode: "0644"
  notify:
    - systemd daemon-reload
    - restart agetty
  become: true

- name: Verify kiosk user's home exists
  stat:
    path: "/home/{{ kiosk_user }}"
  register: kiosk_home

- name: Fail if kiosk user/home missing
  fail:
    msg: "User {{ kiosk_user }} or /home/{{ kiosk_user }} not found. Create the user or override kiosk_user."
  when: not kiosk_home.stat.exists

- name: Install ~/.xinitrc
  template:
    src: xinitrc.j2
    dest: "/home/{{ kiosk_user }}/.xinitrc"
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
    mode: "0755"

- name: Install ~/.bash_profile to auto-run startx
  template:
    src: bash_profile.j2
    dest: "/home/{{ kiosk_user }}/.bash_profile"
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
    mode: "0644"

- name: Summary (reboot recommended)
  debug:
    msg: >
      Kiosk ready for user {{ kiosk_user }} on {{ autologin_tty }}.
      On reboot, Matchbox + Onboard will start and Chromium will open {{ kiosk_url }} in kiosk mode.
