---
- name: Converge user_account
  hosts: localhost
  connection: local
  gather_facts: true
  become: true

  vars:
    linux_admin_group: "{{ 'wheel' if ansible_facts['os_family'] == 'RedHat' else 'sudo' }}"
    managed_users:
      - name: ansible_molecule_user
        state: present
        shell: /bin/bash
        create_home: true
        password_lock: true
        groups:
          - "{{ linux_admin_group }}"
        append_groups: true
        passwordless_sudo: true
        authorized_keys: []
        exclusive_keys: false

  roles:
    - role: user_account
