- name: Restart Docker
  service:
    name: docker
    state: restarted
    enabled: true

- name: Reboot System
  reboot:
    reboot_timeout: 600
    pre_reboot_delay: 10
    post_reboot_delay: 30
    test_command: whoami
  when: allow_reboot | default(true) | bool

- name: Apply netplan
  command: netplan apply
