---
# Server/runtime host package setup
system_host_packages: []

# Application host paths
system_host_app_root: /opt/apps
system_host_app_root_owner: root
system_host_app_root_group: root
system_host_app_root_mode: "0755"

# Deploy/runtime user
system_host_deploy_user: deploy

# Docker
system_host_install_docker: true
system_host_docker_package_method: distro
system_host_docker_packages:
  - docker.io
  - docker-compose-plugin

system_host_docker_service_name: docker
system_host_docker_users:
  - "{{ system_host_deploy_user }}"
