- name: Ensure local SSH key directory exists
  file:
    path: files/ssh_keys
    state: directory
    mode: '0755'
  delegate_to: localhost
  run_once: true
  when: generate_ansible_ssh_key | default(false) | bool

- name: Check if SSH key already exists
  stat:
    path: files/ssh_keys/ansible
  register: ansible_ssh_key_stat
  delegate_to: localhost
  run_once: true
  when: generate_ansible_ssh_key | default(false) | bool

- name: Generate SSH key for ansible user (on control node)
  command: ssh-keygen -t ed25519 -f files/ssh_keys/ansible -N ''
  args:
    creates: files/ssh_keys/ansible
  delegate_to: localhost
  run_once: true
  when:
    - generate_ansible_ssh_key | default(false) | bool
    - not ansible_ssh_key_stat.stat.exists

- name: Set permissions on generated SSH key files
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: files/ssh_keys/ansible, mode: '0600' }
    - { path: files/ssh_keys/ansible.pub, mode: '0644' }
  delegate_to: localhost
  run_once: true
  when: generate_ansible_ssh_key | default(false) | bool
