- name: Attach GPU passthrough XML to VM with fallback
  block:
    - name: Copy reviewed static GPU passthrough XML
      copy:
        src: gpu-passthrough.xml
        dest: /etc/libvirt/qemu/gpu-passthrough.xml
        mode: "0644"

    - name: Attach GPU passthrough device to VM
      command: virsh attach-device win10 /etc/libvirt/qemu/gpu-passthrough.xml --persistent

  rescue:
    - name: Attachment failed — rebind GPU
      command: /usr/local/bin/rebind_gpu.sh

    - name: Log failure to attach GPU
      debug:
        msg: "Failed to attach GPU passthrough device. GPU rebind attempted."

  always:
    - name: Always rebind GPU after device attach block
      command: /usr/local/bin/rebind_gpu.sh
