---
backup_sync_jobs: "{{ sync_jobs | default([]) }}"

backup_sync_install_packages: true

backup_sync_rsync_package: rsync
backup_sync_cron_package: "{{ 'cronie' if ansible_os_family == 'RedHat' else 'cron' }}"
backup_sync_cron_service_name: "{{ 'crond' if ansible_os_family == 'RedHat' else 'cron' }}"

backup_sync_default_rsync_opts:
  - "--archive"
  - "--compress"

backup_sync_checksum: true
backup_sync_delete: false
backup_sync_links: false
backup_sync_recursive: true
backup_sync_owner: false
backup_sync_group: false
backup_sync_perms: false
backup_sync_times: false

backup_sync_continue_on_error: true

backup_cron_user: root
backup_script_dir: /usr/local/bin
backup_install_scripts: true

backup_cron_jobs: []
