# === SSH key generation block (only runs if ssh_keys_to_generate is defined) ===
- block:

    # --- Ensure the SSH key directory exists on the control node ---
    - name: Ensure local SSH key directory exists
      file:
        path: "{{ ssh_key_dir }}"
        state: directory
        mode: '0700'
      delegate_to: localhost
      run_once: true

    # --- Check if each key already exists ---
    - name: Check if SSH key already exists
      stat:
        path: "{{ ssh_key_dir }}/{{ item }}"
      loop: "{{ ssh_keys_to_generate }}"
      register: existing_keys
      delegate_to: localhost
      run_once: true

    # --- Generate missing SSH keys ---
    - name: Generate missing SSH keys
      command: >
        ssh-keygen
        -t {{ ssh_key_type | default('ed25519') }}
        {% if ssh_key_type == 'rsa' %}
        -b {{ ssh_key_bits | default(4096) }}
        {% endif %}
        -f "{{ ssh_key_dir }}/{{ item }}"
        -N ''
        -C "{{ ssh_key_comment | default('Generated by Ansible') }}"
      args:
        creates: "{{ ssh_key_dir }}/{{ item }}"
      loop: "{{ ssh_keys_to_generate }}"
      when: existing_keys.results[loop.index0].stat.exists == false
      delegate_to: localhost
      run_once: true

    # --- Set secure permissions on the generated SSH key files ---
    - name: Set permissions on SSH key files
      file:
        path: "{{ item.path }}"
        mode: "{{ item.mode }}"
      loop: >-
        {{
          ssh_keys_to_generate
          | map('regex_replace', '^(.*)$', ssh_key_dir + '/\\1')
          | map('extract', [{'path': item, 'mode': '0600'}, {'path': item + '.pub', 'mode': '0644'}])
          | flatten
        }}
      delegate_to: localhost
      run_once: true

    # --- Debug: Show a summary of what was generated ---
    - name: Debug summary of generated SSH keys
      debug:
        msg: >-
          SSH keys generated by Ansible:
          {% for key in ssh_keys_to_generate %}
            - {{ ssh_key_dir }}/{{ key }}.pub
          {% endfor %}
      delegate_to: localhost
      run_once: true

  when: ssh_keys_to_generate is defined
