- name: Ensure SSH key directory exists
  file:
    path: "{{ ssh_key_dir }}"
    state: directory
    mode: '0700'
  delegate_to: localhost
  run_once: true
  when: ssh_key_generate | bool

- name: Check if SSH private key exists
  stat:
    path: "{{ ssh_key_private_path }}"
  register: ssh_private_key_stat
  delegate_to: localhost
  run_once: true
  when: ssh_key_generate | bool

- name: Generate SSH key pair
  command: >
    ssh-keygen -t {{ ssh_key_type }} -b {{ ssh_key_bits }} -f {{ ssh_key_private_path }} -N '' -C "{{ ssh_key_comment }}"
  args:
    creates: "{{ ssh_key_private_path }}"
  delegate_to: localhost
  run_once: true
  when:
    - ssh_key_generate | bool
    - not ssh_private_key_stat.stat.exists

- name: Set permissions on generated SSH key files
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: "{{ ssh_key_private_path }}", mode: '0600' }
    - { path: "{{ ssh_key_public_path }}", mode: '0644' }
  delegate_to: localhost
  run_once: true
  when: ssh_key_generate | bool
