# === Generate multiple SSH keypairs on the control node (localhost only) ===
# This task runs only if `ssh_keys_to_generate` is defined and contains a list of SSH key names.
- block:

    # --- Ensure the SSH key directory exists ---
    - name: Ensure local SSH key directory exists
      file:
        path: "{{ ssh_key_dir }}"
        state: directory
        mode: '0700'
      delegate_to: localhost
      run_once: true

    # --- Check if each key already exists ---
    - name: Check if SSH key already exists
      stat:
        path: "{{ ssh_key_dir }}/{{ item }}"
      loop: "{{ ssh_keys_to_generate }}"
      register: existing_keys
      delegate_to: localhost
      run_once: true

    # --- Generate SSH keys only if they don't already exist ---
    - name: Generate missing SSH keys
      command: >
        ssh-keygen
        -t {{ ssh_key_type | default('ed25519') }}
        {% if ssh_key_type == 'rsa' %}
        -b {{ ssh_key_bits | default(4096) }}
        {% endif %}
        -f "{{ ssh_key_dir }}/{{ item.0 }}"
        -N ''
        -C "{{ ssh_key_comment | default('Generated by Ansible') }}"
      args:
        creates: "{{ ssh_key_dir }}/{{ item.0 }}"
      loop: "{{ ssh_keys_to_generate | zip(existing_keys.results) | list }}"
      when: not item.1.stat.exists
      delegate_to: localhost
      run_once: true

    # --- Build permission list for private and public key files ---
    - name: Build list of SSH key file permission entries
      set_fact:
        ssh_key_permissions: >-
          [{% for key in ssh_keys_to_generate %}
            {"path": "{{ ssh_key_dir }}/{{ key }}", "mode": "0600"},
            {"path": "{{ ssh_key_dir }}/{{ key }}.pub", "mode": "0644"}
            {% if not loop.last %},{% endif %}
          {% endfor %}]
      delegate_to: localhost
      run_once: true
      when: ssh_keys_to_generate is defined

    # --- Set permissions on the generated key files ---
    - name: Set permissions on generated SSH key files
      file:
        path: "{{ item.path }}"
        mode: "{{ item.mode }}"
      loop: "{{ ssh_key_permissions }}"
      delegate_to: localhost
      run_once: true

    # --- Debug summary of generated keys ---
    - name: Debug summary of generated SSH keys
      debug:
        msg: >-
          SSH keys generated on control node:
          {% for key in ssh_keys_to_generate %}
            - {{ ssh_key_dir }}/{{ key }}.pub
          {% endfor %}
      delegate_to: localhost
      run_once: true

  when: ssh_keys_to_generate is defined
