# ================================================================
# TASK: Generate SSH keypairs on the control node
#
# This task file assumes the following variables are defined
# (typically in group_vars/all.yml or group_vars/control.yml):
#
#   ssh_key_dir          # e.g., "{{ lookup('env','HOME') }}/.ssh"
#   ssh_keys_to_generate # list of key‐names, e.g. ['host_systems','github']
#   ssh_key_type         # e.g., 'ed25519'  (default if undefined)
#   ssh_key_bits         # e.g., 4096       (only used if type is 'rsa')
#   ssh_key_comment      # e.g., 'Managed by Ansible'
#
# Only runs when ssh_keys_to_generate is defined and non‐empty.
# ================================================================

- block:
    # ------------------------------------------------------------
    # 1) Ensure the SSH key directory exists, with 0700 permissions
    # ------------------------------------------------------------
    - name: Ensure local SSH key directory exists
      file:
        path: "{{ ssh_key_dir }}"
        state: directory
        mode: "0700"
      delegate_to: localhost
      run_once: true

    # ------------------------------------------------------------
    # 2) Generate each keypair only if it’s missing
    #    Uses community.crypto.openssh_keypair for idempotency
    # ------------------------------------------------------------
    - name: Generate missing SSH keypairs via openssh_keypair
      community.crypto.openssh_keypair:
        # Private‐key path (public key will be "<path>.pub")
        path: "{{ ssh_key_dir }}/{{ item }}"
        type: "{{ ssh_key_type | default('ed25519') }}"
        size: "{{ ssh_key_bits | default(4096) }}"
        comment: "{{ ssh_key_comment | default('Generated by Ansible') }}"
        mode: "0600"
        force: false
      loop: "{{ ssh_keys_to_generate }}"
      delegate_to: localhost
      run_once: true

    # ------------------------------------------------------------
    # 3) Ensure each public key has 0644 permissions
    # ------------------------------------------------------------
    - name: Ensure public key files are world-readable
      file:
        path: "{{ ssh_key_dir }}/{{ item }}.pub"
        mode: "0644"
      loop: "{{ ssh_keys_to_generate }}"
      delegate_to: localhost
      run_once: true

    # ------------------------------------------------------------
    # 4) Debug summary of all public keys present
    # ------------------------------------------------------------
    - name: Debug summary of generated SSH keys
      debug:
        msg: >-
          SSH keypairs now exist under {{ ssh_key_dir }}:
          {% for key in ssh_keys_to_generate %}
            - {{ ssh_key_dir }}/{{ key }}.pub
          {% endfor %}
      delegate_to: localhost
      run_once: true

  when:
    - ssh_keys_to_generate is defined
    - ssh_keys_to_generate | length > 0

- name: Skiping SSH key generation when no keys are defined
  debug:
    msg: "No SSH keys to generate; skipping generate_ssh_keys task."
  when: ssh_keys_to_generate is not defined or ssh_keys_to_generate | length == 0
  delegate_to: localhost
  run_once: true
