# === Inject a single SSH public key per system user ===
# Requires `system_user.name` and `system_user.ssh_public_key_path` to be defined.
# Key is read from control node and installed on the remote host.

- block:

    # --- Debug info before adding key ---
    - name: Debug SSH key setup intent
      debug:
        msg: >-
          Installing SSH key for user '{{ system_user.name }}' on host '{{ inventory_hostname }}'
          Using public key file: '{{ system_user.ssh_public_key_path }}'

    # --- Add the key to the user's authorized_keys ---
    - name: Add SSH public key from file
      authorized_key:
        user: "{{ system_user.name }}"
        key: "{{ lookup('file', system_user.ssh_public_key_path) }}"
        state: present
      when:
        - system_user.ssh_public_key_path is defined
        - lookup('file', system_user.ssh_public_key_path, errors='ignore') != ''
      become: true

  when: enable_ssh_key_management | default(false) | bool
