# === Inject SSH key for a single system user from a file ===
- block:

    - name: Add SSH public key for system user from file
      authorized_key:
        user: "{{ system_user.name }}"
        key: "{{ lookup('file', system_user.ssh_public_key_path) }}"
        state: present
      when:
        - system_user.ssh_public_key_path is defined
        - lookup('file', system_user.ssh_public_key_path, errors='ignore') != ''
      become: true

  when: enable_ssh_key_management | default(false) | bool
