# === Inject a single SSH public key per system user ===
# Requires `system_user.name` and `system_user.ssh_public_key_path` to be defined.
# Key is read from control node and installed on the remote host.

- block:

    # --- Debug info before adding key ---
    - name: Debug SSH key setup intent
      debug:
        msg: >-
          Installing SSH key for user '{{ system_user.name }}' on host '{{ inventory_hostname }}'
          Using public key file: '{{ system_user.ssh_public_key_path }}'

    # --- Add the key to the user's authorized_keys ---
    - name: Add SSH public key from file
      authorized_key:
        user: "{{ system_user.name }}"
        key: "{{ lookup('file', system_user.ssh_public_key_path) }}"
        state: present
      when:
        - system_user.ssh_public_key_path is defined
        - lookup('file', system_user.ssh_public_key_path, errors='ignore') != ''
      become: true

  when: enable_ssh_key_management | default(false) | bool


- name: Generate Ansible ssh-keypair
  community.crypto.openssh_keypair:
    path: "/home/{{ user }}/.ssh/application"
    type: ed25519
    state: present
    size: 4096
  become_user: "{{ user }}"

- name: Generate GitHub ssh-keypair
  community.crypto.openssh_keypair:
    path: "/home/{{ user }}/.ssh/github"
    type: ed25519
    state: present
    size: 4096
  become_user: "{{ user }}"

- name: GENERATE ANSIBLE SSH KEYPAIR
  community.crypto.openssh_keypair:
    path: "/home/{{ user_name }}/.ssh/reactapp"
    type: ed25519
    state: present
    size: 4096
  become_user: "{{ user }}"

- name: GENERATE GITHUB OPENSSH KEYPAIR
  community.crypto.openssh_keypair:
    path: "/home/{{ user_name }}/.ssh/fastapi"
    type: ed25519
    state: present
    size: 4096
  become_user: "{{ user }}"

- name: Generate ssh Config File
  template:
    src: "templates/ssh_config.j2"
    dest: "/home/{{ user }}/.ssh/config"
    owner: "{{ user }}"
  become_user: "{{ user }}"

- name: Evaluating the authentication agent & adding the key...
  shell: |
    eval "$(ssh-agent)"
    ssh-add "/home/{{ user }}/.ssh/github_key"
    ssh-add "/home/{{ user }}/.ssh/application_key"
    ssh-add "/home/{{ user }}/.ssh/react"
    ssh-add "/home/{{ user }}/.ssh/fastapi"
  become_user: "{{ user }}"
