- name: Merge system_user with default options and apply additional groups
  set_fact:
    final_user: "{{ default_user_options | combine(system_user, recursive=True) | combine({'groups': merged_groups}) }}"
  vars:
    merged_groups: "{{ (system_user.groups | default([])) + (additional_groups | default([])) | unique }}"

# === Ensure the system user account exists ===
- name: Create the system user
  user:
    name: "{{ final_user.name }}"
    shell: "{{ final_user.shell }}"
    create_home: "{{ final_user.create_home }}"
    groups: "{{ final_user.groups }}"
    system: "{{ final_user.system | default(false) }}"
    password_lock: "{{ final_user.lock_password | default(false) }}"
    uid: "{{ final_user.uid | default(omit) }}"
    group: "{{ final_user.primary_group | default(omit) }}"
  become: true
