ansible_host: server2.local  # or IP address if no DNS

fastapi_apps:
  - name: labelapi
    repo: https://github.com/yourorg/labelapi.git
    path: /opt/labelapi
    branch: stable
    port: "8001:8000"
    env_file: "/home/ubuntu/.application/app_control/env_vars/fastAPI.env"
    models_src: "/home/ubuntu/.application/app_files/data_models_layer/"
    models_dest: "app/physical_layer/data_models_layer/"
    network: application_network

  - name: palletapi
    repo: https://github.com/yourorg/palletapi.git
    path: /opt/palletapi
    branch: update
    port: "8002:8000"
    network: application_network
