---
- name: "Creating user: {{ user_name }}"
  ansible.builtin.user:
    state: present
    name: "{{ user_name }}"
    create_home: yes
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/rsa_id
    groups:
    - docker
    - sudo

- name: "Creating directory for application data in {{ user_name }} home directory"
  file:
    path: "/home/{{ user_name }}/{{ item.path }}"
    mode: "{{ item.attrs }}"
    state: directory
    recurse: yes
  with_items:
    "{{ application_directories }}"

