---
- name: DOWNLOADING CONFIG DATA
  ansible.builtin.copy:
    remote_src: yes
    src: "/home/{{ user_name }}/.application/server_config_files/fastAPI.env"
    dest: "/home/{{ user_name }}/{{ item.repo_name }}/app/.env"
  with_items:
    - "{{ fastapi_repo }}"
    - "{{ fastapi_update_repo }}"

  ansible.builtin.copy:
    remote_src: yes
    src: "/home/{{ user_name }}/.application/server_config_files/data_models_layer/"
    dest: "/home/{{ user_name }}/{{ item.repo_name }}/app/physical_layer/data_models_layer/"
  with_items:
    - "{{ fastapi_repo }}"
    - "{{ fastapi_update_repo }}"

- name: Create docker compose file
  ansible.builtin.template:
    src: "templates/fastapi_docker_compose.j2"
    dest: "/home/{{ user_name }}/{{ item.repo_name }}/docker-compose.yml"
  with_items:
    - "{{ fastapi_repo }}"
    - "{{ fastapi_update_repo }}"
