---
- name: DOWNLOADING CONFIG DATA
  ansible.builtin.copy:
    remote_src: yes
    src: "/home/{{ item.user_name }}/.application/server_config_files/fastAPI.env"
    dest: "/home/{{ item.user_name }}/{{ item.repo_name }}/app/.env"
  with_items:
    - "{{ fastapi_stable }}"
    - "{{ fastapi_update }}"

  ansible.builtin.copy:
    remote_src: yes
    src: "/home/{{ item.user_name }}/.application/server_config_files/data_models_layer/"
    dest: "/home/{{ item.user_name }}/{{ item.repo_name }}/app/physical_layer/data_models_layer/"
  with_items:
    - "{{ fastapi_stable }}"
    - "{{ fastapi_update }}"
