---
service_name: databaseapi

fastapi_repo_url: "git@github.com:kfcodes/fastapi.git"

fastapi_tags:
  stable: "v0.02"
  update: "rc0.1.4.3"

ports:
  stable: 8011
  update: 8012

container_service_manage_dockerfile: true
container_internal_port: 8000
container_service_uvicorn_app: "app:app"

container_services:
  - name_suffix: stable
    repo: "{{ fastapi_repo_url }}"
    version: "{{ fastapi_tags.stable }}"
    host_port: "{{ ports.stable }}"
    container_port: "{{ container_internal_port }}"

  - name_suffix: update
    repo: "{{ fastapi_repo_url }}"
    version: "{{ fastapi_tags.update }}"
    host_port: "{{ ports.update }}"
    container_port: "{{ container_internal_port }}"
