---
service_name: frontend

react_repo_url: "git@github.com:kfcodes/reactapp.git"

react_tags:
  stable: "v0.02.01-router_hotfix"
  update: "rc0.02.02"

ports:
  stable: 3000
  update: 3001

# Frontend should normally use its own repo Dockerfile.
container_service_manage_dockerfile: false
container_internal_port: 3000

container_services:
  - name_suffix: stable
    repo: "{{ react_repo_url }}"
    version: "{{ react_tags.stable }}"
    host_port: "{{ ports.stable }}"
    container_port: "{{ container_internal_port }}"

  - name_suffix: update
    repo: "{{ react_repo_url }}"
    version: "{{ react_tags.update }}"
    host_port: "{{ ports.update }}"
    container_port: "{{ container_internal_port }}"
