---
- name: Ensure fastAPI git repo is present
  ansible.builtin.git:
    repo: 'https://github.com/kfcodes/pandas_scripts.git'
    dest: /home/test/fastAPI/
- name: Install specified python requirements for fastAPI
  ansible.builtin.pip:
    virtualenv: /home/test/fastAPI/venv
    virtualenv_command: python3 -m venv
    requirements: /home/test/fastAPI/requirements.txt
    virtualenv: /home/test/fastAPI/venv
    state: latest
