---
- name: Install backup sync dependencies
  ansible.builtin.import_tasks: packages.yml
  when: backup_sync_install_packages | bool
  tags: [backup_sync, backup, sync, packages]

- name: Validate backup_sync inputs
  ansible.builtin.import_tasks: validate.yml
  tags: [backup_sync, sync, backup, cron, scripts]

- name: Run sync jobs
  ansible.builtin.import_tasks: sync_jobs.yml
  when: backup_sync_jobs | length > 0
  tags: [sync, backup_sync]

- name: Install backup scripts
  ansible.builtin.import_tasks: install_scripts.yml
  when:
    - backup_install_scripts | bool
    - backup_cron_jobs | length > 0
  tags: [scripts, cron, backup]

- name: Configure backup cron jobs
  ansible.builtin.import_tasks: cron_jobs.yml
  when: backup_cron_jobs | length > 0
  tags: [cron, backup]
