---
- name: GENERATE ANSIBLE SSH KEYPAIR
  community.crypto.openssh_keypair:
    path: "/home/{{ user_name }}/.ssh/reactapp"
    type: ed25519
    state: present
    size: 4096
  become_user: "{{ user_name }}"

- name: GENERATE GITHUB OPENSSH KEYPAIR
  community.crypto.openssh_keypair:
    path: "/home/{{ user_name }}/.ssh/fastapi"
    type: ed25519
    state: present
    size: 4096
  become_user: "{{ user_name }}"

- name: Evaluating the authentication agent & adding the key...
  shell: |
    eval "$(ssh-agent)"
    ssh-add "/home/{{ user_name }}/.ssh/react"
    ssh-add "/home/{{ user_name }}/.ssh/fastapi"
  become_user: "{{ user_name }}"
