---
- name: Updated to the latest version of the React App
  ansible.builtin.git:
    repo: 'https://github.com/kfcodes/production_documentation.git'
    dest: /home/{{ user_name }}/react/
    single_branch: yes
    force: yes
    version: production

# - name: Update React packages based on package.json to their latest version
#   community.general.npm:
#     path: /home/{{ user_name }}/ReactApp/
#     state: latest
