---
dependency:
  name: galaxy

driver:
  name: default

platforms:
  - name: localhost

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "/home/m/ansible/roles"
  inventory:
    host_vars:
      localhost:
        ansible_connection: local

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - syntax
    - converge
    - verify
