---
- name: Get the latest version of the fastAPI App
  ansible.builtin.git:
    repo: 'https://github.com/kfcodes/pandas_scripts.git'
    dest: /home/fastAPI/
    single_branch: yes
    version: main

- name: Install specified python requirements for fastAPI
  ansible.builtin.pip:
    virtualenv: /home/fastAPI/venv
    virtualenv_command: python3 -m venv
    requirements: /home/fastAPI/requirements.txt
    virtualenv: /home/fastAPI/venv
    state: latest
