---
- name: systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: restart agetty
  ansible.builtin.systemd:
    name: "getty@{{ kiosk_autologin_tty }}.service"
    state: restarted
  become: true
  when: kiosk_restart_getty | bool
