- name: Ensure base and compose directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ react_app_base_path }}"
    - "{{ react_app_compose_path }}"

- name: Copy Docker Compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ react_app_compose_path }}/docker-compose.yml"
    mode: "0644"

- name: Copy .env file if it exists
  copy:
    src: env
    dest: "{{ react_app_env_file }}"
    mode: "0644"
  when: lookup('ansible.builtin.file', 'files/env', errors='ignore') is defined
