---

# === UPDATE SYSTEM ===

- name: Update packages (Debian)
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes
    autoclean: yes
  register: update_result
  when: ansible_os_family == "Debian"
  notify: Reboot System

- name: Upgrade packages (RedHat/Fedora)
  dnf:
    name: "*"
    state: latest
    update_cache: yes
  register: update_result
  when: ansible_os_family == "RedHat"
  notify: Reboot System

# === COMBINE AND INSTALL PACKAGES ===

- name: Combine default + group-specific packages
  set_fact:
    packages_to_install: "{{ default_packages + (group_packages | default([])) }}"

- name: Install combined packages (Cross-platform)
  package:
    name: "{{ packages_to_install }}"
    state: latest

# === DOCKER SETUP (Ubuntu Only) ===

- block:
    - name: Ensure keyring dir exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Check if Docker GPG key exists
      stat:
        path: /etc/apt/keyrings/docker.gpg
      register: docker_gpg

    - name: Add Docker GPG key if missing
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'
      when: not docker_gpg.stat.exists

    - name: Add Docker APT repo
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        filename: docker
        state: present

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes
      notify: Restart Docker

    - name: Install Docker Compose (Debian and RedHat)
      package:
        name: docker-compose
        state: latest
      when:
        - install_docker | bool
        - ansible_os_family in ["Debian", "RedHat"]

  when:
    - install_docker | bool
    - ansible_distribution == "Ubuntu"

# === LOG WHEN REBOOT IS SKIPPED ===

- name: Log message when reboot is skipped
  debug:
    msg: "Reboot skipped for {{ inventory_hostname }} (allow_reboot is false)."
  when:
    - not allow_reboot | default(true) | bool
