---
- name: Check React app package.json exists
  ansible.builtin.stat:
    path: "{{ system_dev_home }}/.reactapp/package.json"
  register: system_dev_react_package_json

- name: Install NPM packages for React app
  community.general.npm:
    path: "{{ system_dev_home }}/.reactapp"
    state: present
  when: system_dev_react_package_json.stat.exists
  become_user: "{{ system_dev_user }}"
  environment:
    HOME: "{{ system_dev_home }}"

- name: Check FastAPI requirements file exists
  ansible.builtin.stat:
    path: "{{ system_dev_home }}/.fastapi/requirements.txt"
  register: system_dev_fastapi_requirements

- name: Install Python requirements for FastAPI
  ansible.builtin.pip:
    requirements: "{{ system_dev_home }}/.fastapi/requirements.txt"
    virtualenv: "{{ system_dev_home }}/.fastapi/.venv"
    virtualenv_command: python3 -m venv
  when: system_dev_fastapi_requirements.stat.exists
  become_user: "{{ system_dev_user }}"
  environment:
    HOME: "{{ system_dev_home }}"
