---
- name: Pull development repositories
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ system_dev_home }}/{{ item.dest }}"
    version: "{{ item.version | default('HEAD') }}"
    accept_hostkey: true
    update: true
  loop: "{{ dev_repositories }}"
  loop_control:
    label: "{{ item.dest }}"
  become_user: "{{ system_dev_user }}"
  environment:
    HOME: "{{ system_dev_home }}"
