---
- name: Create base development directories
  ansible.builtin.file:
    path: "{{ system_dev_home }}/{{ item.path }}"
    mode: "{{ item.attrs | default('0755') }}"
    state: directory
    owner: "{{ system_dev_user }}"
    group: "{{ system_dev_user }}"
  loop: "{{ application_directories }}"

- name: Ensure repository parent directories exist
  ansible.builtin.file:
    path: "{{ (system_dev_home ~ '/' ~ item.dest) | dirname }}"
    state: directory
    owner: "{{ system_dev_user }}"
    group: "{{ system_dev_user }}"
    mode: "0755"
  loop: "{{ dev_repositories }}"
