# - name: Clone local config repos
#   import_tasks: local_repos.yml
#   tags: [local_repos]

- name: Configure GitHub SSH access
  import_tasks: github_ssh.yml
  tags: [github_ssh, ssh, git]
  when: devtools_github_ssh_enabled | bool

- name: Apply the dotfile configs
  import_tasks: dotfiles.yml
  tags: [dotfiles]

- name: Apply environment file links
  import_tasks: env_links.yml
  tags: [env]

- name: Clone dev repositories
  import_tasks: clone_repositories.yml
  tags: [repos]

- name: Set up application and package dependencies
  import_tasks: app_setup.yml
  tags: [apps]
