---
- name: systemd daemon-reload
  systemd:
    daemon_reload: true
  become: true

- name: restart agetty
  systemd:
    name: "getty@{{ autologin_tty }}.service"
    state: restarted
  become: true
