---
- name: Playbook to manage application data and backups
  hosts: host_servers
  become: true

  vars_files:
    - ../vars/main.yml

  tasks:
    - name: Update host system
      include_role:
        name: update_system

    - name: Update local cron jobs
      include_role:
        name: app_cron_jobs

    - name: Sync application data
      include_role:
        name: manage_app_data
