---
- name: Synchronize data between local system and server
  hosts: db_servers

  vars:
    web_app_usr: "application"
    # GIT URL PATHS
    fastapi_repo_url: "https://github.com/kfcodes/pandas_scripts.git"
    react_repo_url: "https://github.com/kfcodes/production_documentation.git"

    # COMMON VARIABLES
    user_name: application
    stable_branch: production
    fastapi_update_tag: dev
    react_update_tag: main

    # REPOSTORY DETAILS
    fastapi_stable: { repo_name: "fastAPI", repo_url: "{{ fastapi_repo_url }}", version: "{{ stable_branch }}", user_name: "{{ user_name }}", port: "8005" }
    fastapi_update: { repo_name: fastAPI_update, repo_url: "{{ fastapi_repo_url }}", version: "{{ fastapi_update_tag }}", user_name: "{{ user_name }}" , port: "8006" }
    react_stable: { repo_name: react, repo_url: "{{ react_repo_url }}", version: "{{ stable_branch }}", user_name: "{{ user_name }}", port: "3002" }
    react_update: { repo_name: react_update, repo_url: "{{ react_repo_url }}", version: "{{ react_update_tag }}", user_name: "{{ user_name }}", port: "3003" }

  roles:
    # - cron_jobs
    # - synchronise_application_data
    # - role: git_pull
    #   become: true
    # - role: prep_fastapi_container
    #   become: true
    #   item : "{{ fastapi_stable }}"
    # - role: prep_fastapi_container
    #   become: true
    #   item : "{{ fastapi_update }}"
    - role: prep_react_container
      become: true
      item : "{{ react_stable }}"
    - role: prep_react_container
      become: true
      item : "{{ react_update }}"
    # - role: pull_docker_image
    #   vars: 
    #     image_name: mariadb
    #     version: latest
    # - build_docker_container
    # - build_docker_container
    # - clone_git_repo
