---
- name: Playbook to pull and manage repositories
  hosts: web_servers

  vars_files:
    - ../vars/main.yml

  roles:
  - cron_jobs
  - synchronise_application_data
  - role: prep_fastapi_container
    become: yes
  - role: prep_react_container
    become: yes
