---
- name: Synchronize data between local system and server
  hosts: db_servers

  vars:
    web_app_usr: "application"


  roles:
    - cron_jobs
    - synchronise_application_data
    - role: update_repos
      become: true
    # - role: pull_docker_image
    #   vars: 
    #     image_name: mariadb
    #     version: latest
    # - build_docker_container
    # - build_docker_container
    # - clone_git_repo
