---
- name: Creating directories on remote server
  hosts: app
  become: yes
  tasks:
    - name: Creating Folders
      file:
        path: /tmp/{{ item.path }} 
        mode: "{{ item.mode  }}"
        state: directory
      with_items:
        - { path: "test_directory_777", mode: "u=rwX,g=rwX,o=rwX" }
        - { path: "test_directory_755", mode: "u=rwX,g=rX,o=rX" }
        - { path: "test_directory_740", mode: "u=rwX,g=r" }
