---
- name: Initialize system configuration
  hosts: system_dev
  gather_facts: true
  become: true

  roles:
    - role: sys_base_config
      vars:
        github_username: johndoe
        github_email: johndoe@example.com
    - usr_mgmt
    # - system_dev_config
