---
- name: Initialize system configuration
  hosts: system_dev
  gather_facts: true
  become: true

  roles:
    - role: system_base_config
      vars:
        github_username: johndoe
        github_email: johndoe@example.com
    - user_management
    # - system_dev_config
