---
- name: "Setting up local Linux machine"
  hosts: localhost
  connection: local 
  become: yes
  tasks:
    - name: create Direcotories
      file:
        path: /tmp/test 
        state: directory
        path: /tmp/{{ item.path }} 
        mode: "{{ item.mode  }}"
        state: directory
      with_items:
        - { path: "test777", mode: "u=rwX,g=rwX,o=rwX" }
        - { path: "test755", mode: "u=rwX,g=rX,o=rX" }
        - { path: "test740", mode: "u=rwX,g=r" }
