---
- name: Deploying application reposotories to application server
  hosts: app
  become: yes
  gather_facts: no

  tasks:
    - name: Ensure fastAPI git repo is present
      ansible.builtin.git:
        repo: 'https://github.com/kfcodes/pandas_scripts.git'
        dest: /home/test/fastAPI/

    - name: Ensure Nodejs API git repo is present
      ansible.builtin.git:
        repo: 'https://github.com/kfcodes/product_database_api.git'
        dest: /home/test/product_database_API/

    - name: Ensure React app git repo is present
      ansible.builtin.git:
        repo: 'https://github.com/kfcodes/production_documentation.git'
        dest: /home/test/front_end/

    - name: Install specified python requirements for fastAPI
      ansible.builtin.pip:
        virtualenv: /home/test/fastAPI/venv
        virtualenv_command: python3 -m venv
        requirements: /home/test/fastAPI/requirements.txt
        virtualenv: /home/test/fastAPI/venv

    - name: Update packages based on package.json to their latest version
      community.general.npm:
        path: /home/test/product_database_API/
        state: latest

    - name: Update React packages based on package.json to their latest version
      community.general.npm:
        path: /home/test/front_end/
        state: latest

    - name: Synchronize local config files with application server
      ansible.posix.synchronize:
        checksum: yes
        src: ~/app_config_files/test.txt
        dest: /home/test/app_config_files/

    - name: Synchronize local production documentation directory with server
      ansible.posix.synchronize:
        checksum: yes
        src: ~/production_documentation/
        dest: /home/test/production_documentation/
