---
- name: Updating and installing packages on development system
  hosts: devservers
  become: yes

  roles:
    - update_system
    - install_development_system_packages
    - configure_development_environment
