# Added task to create directories on local system
---
- name: "UPDATING AND INSTALLING PACKAGES ON SYSTEM"
  hosts: localhost
  connection: local 
  become: yes

  tasks:
    - name: UPDATEING AND UPGRADING SYSTEM PACKAGES
      pacman:
        update_cache: yes
        upgrade: yes
