---
- name: Updating and installing packages on development system
  hosts: dev
  become: yes

  tasks:
    - name: updating and upgrading system packages
      ansible.builtin.package:
        update_cache: yes
        upgrade: yes
