# Added task to create directories on local system
---
- name: "updating and installing packages on development system"
  hosts: localhost
  connection: local 
  become: yes

  tasks:
    - name: updating and upgrading system packages
      pacman:
        update_cache: yes
        upgrade: yes
