---
- name: Provisioning server for hosting application
  hosts: app
  become: yes

  pre_tasks:
    - name: Updating installed packages
      ansible.builtin.package:
        update_cache: yes
        upgrade: yes

  tasks:
    - name: Installing required packages
      ansible.builtin.package:
        name: 
          - htop
          - tmux
          - neovim
          - rsync
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - ripgrep
        state: latest
        update_cache: true

  roles:
    - docker_ubuntu_install
