---
- name: Deploying application reposotories to application server
  hosts: app
  become: yes
  gather_facts: no

  tasks:
    - name: Ensure fastAPI git repo is present
      ansible.builtin.git:
        repo: 'https://github.com/kfcodes/pandas_scripts.git'
        dest: /home/test/fastAPI/

    - name: Ensure Nodejs API git repo is present
      ansible.builtin.git:
        repo: 'https://github.com/kfcodes/product_database_api.git'
        dest: /home/test/product_database_API/
        version: removing_unused_routes

    - name: Ensure React app git repo is present
      ansible.builtin.git:
        repo: 'https://github.com/kfcodes/production_documentation.git'
        dest: /home/test/front_end/
        version: new_api_routes

    - name: Install specified python requirements for fastAPI
      ansible.builtin.pip:
        virtualenv: /home/test/fastAPI/venv
        virtualenv_command: python3 -m venv
        requirements: /home/test/fastAPI/requirements.txt
        virtualenv: /home/test/fastAPI/venv
        state: latest

    - name: Update packages based on package.json to their latest version
      community.general.npm:
        path: /home/test/product_database_API/
        state: latest

    - name: Update React packages based on package.json to their latest version
      community.general.npm:
        path: /home/test/front_end/
        state: latest
