---
- name: Provision Linux System For Hosting Application
  hosts: web_servers
  become: yes

  vars_files:
    - ../vars/main.yml

  tasks:
    - name: UPDATE HOST SYSTEM
      include_role:
        name: update_system

    - name: Install packages for host system
      include_role:
        name: install_packages

    - name: Install and configure docker on ubuntu
      include_role:
        name: docker_for_ubuntu

    - name: CREATE USERS AND DIRECTORIES
      include_role:
        name: host_usr_config

    - name: GENERATE SSH KEY PAIRS
      include_role:
        name: ssh_keys

    - name: Print instructions to the user
      ansible.builtin.debug:
        msg: 'Next steps (1) Copy the public ssh keys to the remote servers and Github (2) Run the app_sync playbook (3) Run docker_update playbook' 
