---
- name: Provisioning server for hosting application
  hosts: web_servers
  become: yes

  vars:
    web_app_usr: "application"

  roles:
    - update_system
    - install_packages
    - docker_for_ubuntu
    - role: usr_and_dirs
      vars: 
        user_name: "{{ web_app_usr }}"

