---
- name: Start application
  hosts: app
  tasks:
    - name: Also specify working directory where running pm2 command
      pm2:
        name: myapp
        state: started
        executable: /home/test/product_database_api/index.js

    #- name: Starting MariaDB
    #- name: Starting fastAPI
    #- name: Starting Nodejs API
    #- name: Starting React app

