---
- name: Initialise the local system
  hosts: control
  become: yes

  vars_files:
    - ../vars/main.yml

  tasks:
    - name: UPDATE LOCAL SYSTEM
      include_role:
        name: update_system

    - name: INSTALL PACKAGES FOR LOCAL SYSTEM
      include_role:
        name: install_packages

    - name: INSTALL AND CONFIGURE DOCKER ON UBUNTU
      include_role:
        name: docker_for_ubuntu

    - name: CREATE USERS AND DIRECTORIES
      include_role:
        name: usr_and_dirs

    - name: GENERATE SSH KEY PAIRS
      include_role:
        name: ssh_keys
