---
- name: Configuring the local system
  hosts: control
  become: yes

  vars_files:
    - ../vars/main.yml

  tasks:
    #    - name: DOWLOAD LOCAL GITHUB REPOS
    #  include_role:
    #    name: local_git_repos

    - name: Configure local system
      include_role:
        name: local_env_config
