---
- name: Provision common managed Linux hosts
  hosts: managed_linux_hosts
  gather_facts: true
  become: true

  tasks:
    - name: Configure base OS
      ansible.builtin.include_role:
        name: system_base
        apply:
          tags:
            - system_base
            - base
      tags:
        - system_base
        - base
        - provision

- name: Provision service runtime hosts
  hosts: service_runtime_hosts
  gather_facts: true
  become: true

  tasks:
    - name: Configure service runtime
      ansible.builtin.include_role:
        name: system_host
        apply:
          tags:
            - system_host
            - service_runtime
            - docker
      tags:
        - system_host
        - service_runtime
        - docker
        - provision

- name: Provision dev / control hosts
  hosts: dev_control_hosts
  gather_facts: true
  become: true

  tasks:
    - name: Configure development users
      ansible.builtin.include_role:
        name: user_account
        apply:
          tags:
            - user_account
            - users
      tags:
        - user_account
        - users
        - provision

    - name: Configure development system
      ansible.builtin.include_role:
        name: system_dev
        apply:
          tags:
            - system_dev
            - github_ssh
            - git
            - repos
            - dotfiles
            - env
            - apps
      tags:
        - system_dev
        - github_ssh
        - git
        - repos
        - dotfiles
        - env
        - apps
        - provision

- name: Provision GPU passthrough hosts
  hosts: vfio_hosts
  gather_facts: true
  become: true

  tasks:
    - name: Configure GPU passthrough
      ansible.builtin.include_role:
        name: vfio_gpu_passthrough
        apply:
          tags:
            - vfio
            - gpu
      tags:
        - vfio
        - gpu
        - provision
