---
  - name: Playbook to pull and manage repositories
    hosts: host_systems
    become: true

    roles:
    - system_update_and_init
    - manage_backups
    - sync_resources
    # - deploy_reactapp_container
    # - deploy_fastapi_container

    - name: PULL THE MOST RECENT FASTAPI REPOSITORY
      include_role:
        name: git_pull_repo
      vars:
        git_repo_name: "{{ fastapi_repo.repo_name }}"
        git_repo_url: "{{ fastapi_repo.repo_url }}"
        git_version: "{{ fastapi_repo.version }}"
        git_user_name: "{{ fastapi_repo.user_name }}"
        git_port: "{{ fastapi_repo.port }}"
        git_repo_key: fastapi
    - name: PULL THE MOST RECENT FASTAPI UPDATE REPOSITORY
      include_role:
        name: git_pull_repo
      vars:
        git_repo_name: "{{ fastapi_update_repo.repo_name }}"
        git_repo_url: "{{ fastapi_update_repo.repo_url }}"
        git_version: "{{ fastapi_update_repo.version }}"
        git_user_name: "{{ fastapi_update_repo.user_name }}"
        git_port: "{{ fastapi_update_repo.port }}"
        git_repo_key: fastapi
    - name: CONFIGURE FASTAPI CONTAINERS
      include_role:
        name: fastapi_docker_container_config

    - name: PULL THE MOST RECENT REACT REPOSITORY
      include_role:
        name: git_pull_repo
      vars:
        git_repo_name: "{{ react_repo.repo_name }}"
        git_repo_url: "{{ react_repo.repo_url }}"
        git_version: "{{ react_repo.version }}"
        git_user_name: "{{ react_repo.user_name }}"
        git_port: "{{ react_repo.port }}"
        git_repo_key: reactapp
    - name: PULL the most recent REACT UPDATE REPOSITORY
      include_role:
        name: git_pull_repo
      vars:
        git_repo_name: "{{ react_update_repo.repo_name }}"
        git_repo_url: "{{ react_update_repo.repo_url }}"
        git_version: "{{ react_update_repo.version }}"
        git_user_name: "{{ react_update_repo.user_name }}"
        git_port: "{{ react_update_repo.port }}"
        git_repo_key: reactapp
    - name: CONFIGURE REACT CONTAINERS
      include_role:
        name: reactapp_docker_container_config
