---
- name: Synchronize data
  hosts: app

  tasks:
  - name: Synchronize local application and config files with remote server
    ansible.posix.synchronize:
      checksum: true
      src: ~/.configFiles/{{ item.name }}
      dest: /home/test/.configFiles/{{ item.dest }}
    with_items:
        - { name: "fastAPI.env", dest: "fastAPI.env"}
        - { name: "fastAPI.env", dest: "fastAPI_2.env"}
        - { name: "test.txt", dest: "fastAPI_2.txt"}
        - { name: "test.txt", dest: "test.txt"}

  - name: Synchronize remote server backup data with local system
    ansible.posix.synchronize:
      checksum: true
      mode: pull
      src: /home/m/sqlBackupData/
      dest: ~/.backupdata/

  - name: Synchronize remote server production documentation with local system
    ansible.posix.synchronize:
      checksum: true
      mode: pull
      src: /home/test/.productionDocumentation/
      dest: ~/.productionDocumentation/
