---
- name: Ensure service directory exists
  ansible.builtin.file:
    path: "{{ container_service_app_path }}"
    state: directory
    owner: "{{ container_service_app_owner }}"
    group: "{{ container_service_app_group }}"
    mode: "{{ container_service_app_mode }}"
  when: container_service_state == 'present'

- name: Clone or update git repository
  ansible.builtin.git:
    repo: "{{ app.repo }}"
    dest: "{{ container_service_app_path }}"
    version: "{{ app.version }}"
    update: true
    force: false
    accept_hostkey: true
  register: repo_result
  when: container_service_state == 'present'
