install_docker: true
allow_reboot: true

docker_service_name: docker

default_packages:
  - curl
  - git
  - vim
  - htop
  - tmux
  - neovim
  - rsync
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - python3-pip
  - virtualenv
  - python3-setuptools
  - ripgrep
  - remmina
  - mariadb-server
  - fuse
  - texlive-full

group_packages: []
