dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: geerlingguy/docker-debian11-ansible
    pre_build_image: true
    privileged: true
    published_ports:
      - 0.0.0.0:2222:22/tcp

provisioner:
  name: ansible
  lint: |
    yamllint .
    ansible-lint .

verifier:
  name: ansible
