# GIT REPO PATH
fastapi_repo_url: "git@github.com:kfcodes/fastapi.git"

# GIT BRANCH DETAILS
fastapi_stable_tag: v0.02
fastapi_update_tag: rc0.1.4.3
default_branch: main

# REPOSITORY DETAILS
fastapi_repo:
  repo_name: "fastAPI"
  repo_url: "{{ fastapi_repo_url }}"
  version: "{{ fastapi_stable_tag }}"
  user_name: "{{ user_name }}"
  port: "8001"
fastapi_update_repo:
  repo_name: "fastAPI_update_2"
  repo_url: "{{ fastapi_repo_url }}"
  version: "{{ fastapi_update_tag }}"
  user_name: "{{ user_name }}"
  port: "8002"
