# GIT BRANCH DETAILS
fastapi_stable_tag: v0.02
fastapi_update_tag: rc0.1.4.3
default_branch: main

# GITHUB URL PATHS
fastapi_repo_url: "git@github.com:kfcodes/fastapi.git"

# USER INFO
local_usr: "m"
user_name: "new_application"
web_app_usr: "application"
pwd: "test"

# REPOSITORY DETAILS
fastapi_repo:
  repo_name: "fastAPI"
  repo_url: "{{ fastapi_repo_url }}"
  version: "{{ fastapi_stable_tag }}"
  user_name: "{{ user_name }}"
  port: "8001"
fastapi_update_repo:
  repo_name: "fastAPI_update_2"
  repo_url: "{{ fastapi_repo_url }}"
  version: "{{ fastapi_update_tag }}"
  user_name: "{{ user_name }}"
  port: "8002"
