# === Ansible SSH and User Settings ===
users:
  - name: appuser
    groups: [docker]

create_internal_users: true

# === System Behavior Flags ===
allow_reboot: true
install_docker: true

# === Network Configuration Defaults ===
netmask: 24
gateway: 192.168.1.1

dns_servers:
  - 1.1.1.1
  - 8.8.8.8

# === File Source Directories on Host System ===
db_backup_dir: /var/backups/db
app_control_dir: /opt/scripts
app_files_dir: /opt/webapp

# === File Sync Job Definitions (Push to Dev System) ===
sync_jobs:
  - name: Push DB backups
    src: "{{ db_backup_dir }}"
    dest: /mnt/devsync/db
    mode: push

  - name: Push control scripts
    src: "{{ app_control_dir }}"
    dest: /mnt/devsync/scripts
    mode: push

  - name: Push application files
    src: "{{ app_files_dir }}"
    dest: /mnt/devsync/webapp
    mode: push

# === Minimal Package Set for Application Hosting ===
host_system_packages:
  - htop
  - tmux
  - neovim
  - rsync
  - ripgrep
  - ranger
  - curl
  - git
  - python3
  - python3-pip
