# === Ansible SSH and User Settings ===
system_user:
  name: devuser
  shell: /bin/bash
  create_home: true
  ssh_public_key_path: "{{ ssh_key_dir }}/host_systems.pub"
  groups:
    - sudo

create_internal_users: false
ssh_key_generate: true

ssh_keys_to_generate:
  - github_4
  - host_systems
  - gitlab

# === System Behavior Flags ===
allow_reboot: true
install_docker: true

# === Source and Destination Paths for File Sync ===
db_backup_source_directory: "{{ sync_source_base }}/db_backups/"
db_backup_destination_directory: "{{ sync_dest_base }}/db/"

app_control_source_directory: "{{ sync_source_base }}/scripts/"
app_control_destination_directory: "{{ sync_dest_base }}/scripts/"

app_files_source_directory: "{{ sync_source_base }}/webapp/"
app_files_destination_directory: "{{ sync_dest_base }}/webapp/"

# === File Sync Job Definitions ===
sync_jobs:
  - name: Sync static web assets
    src: ./static/
    dest: /var/www/static/

  - name: Sync config templates
    src: ./config/
    dest: /etc/myapp/config/
    rsync_opts:
      - "--exclude=secrets.env"

  - name: Sync DB backups
    src: "{{ db_backup_source_directory }}"
    dest: "{{ db_backup_destination_directory }}"
    mode: pull

  - name: Sync control scripts
    src: "{{ app_control_source_directory }}"
    dest: "{{ app_control_destination_directory }}"
    mode: pull

  - name: Sync application files
    src: "{{ app_files_source_directory }}"
    dest: "{{ app_files_destination_directory }}"
    mode: pull

# === CLI Tool Packages ===
cli_tools:
  - python3-venv
  - fd-find
  - bat
  - jq
  - man-db

# === Python Development Packages ===
python_tools:
  - python3-pip
  - virtualenv
  - python3-setuptools
  - python3-dev
  - python3-wheel
  - pipx

# === System Utilities ===
system_utils:
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - fuse
  - net-tools
  - iproute2
  - lsof
  - iotop
  - ncdu
  - sysstat
  - glances
  - rsync
  - acl

# === Graphical Tools and Fonts ===
gui_utils:
  - remmina
  - texlive-full
  - filezilla
  - darktable

# === Local Database Tools ===
db_tools:
  - mariadb-server

# === Combined Package Set for Installation ===
local_system_packages: >-
  {{ cli_tools + gui_utils + db_tools }}
#   {{ cli_tools + python_tools + system_utils +
#      gui_utils + db_tools }}
