# === Local User Identity ===
local_usr: m

install_docker: true
force_docker_reinstall: false

# === Sync Directory Base Paths ===
sync_source_base: "/opt"
sync_dest_base: "/mnt/devsync"

# === Source and Destination Paths for File Sync ===
db_backup_source_directory: "{{ sync_source_base }}/db_backups/"
db_backup_destination_directory: "{{ sync_dest_base }}/db/"

app_control_source_directory: "{{ sync_source_base }}/scripts/"
app_control_destination_directory: "{{ sync_dest_base }}/scripts/"

app_files_source_directory: "{{ sync_source_base }}/webapp/"
app_files_destination_directory: "{{ sync_dest_base }}/webapp/"

# === File Sync Job Definitions ===
sync_jobs:
  - name: Sync DB backups
    src: "{{ db_backup_source_directory }}"
    dest: "{{ db_backup_destination_directory }}"
    mode: pull

  - name: Sync control scripts
    src: "{{ app_control_source_directory }}"
    dest: "{{ app_control_destination_directory }}"
    mode: pull

  - name: Sync application files
    src: "{{ app_files_source_directory }}"
    dest: "{{ app_files_destination_directory }}"
    mode: pull

# === CLI Tool Packages ===
cli_tools:
  - python3-venv
  - fd-find
  - bat
  - jq
  - man-db

# === Python Development Packages ===
python_tools:
  - python3-pip
  - virtualenv
  - python3-setuptools
  - python3-dev
  - python3-wheel
  - pipx

# === System Utilities ===
system_utils:
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - fuse
  - net-tools
  - iproute2
  - lsof
  - iotop
  - ncdu
  - sysstat
  - glances
  - rsync
  - acl

# === Graphical Tools and Fonts ===
gui_utils:
  - remmina
  - texlive-full
  - gnome-system-monitor
  - meld
  - filezilla

# === Local Database Tools ===
db_tools:
  - mariadb-server

# === Combined Package Set for Installation ===
# local_system_packages: >-
#   {{ cli_tools + python_tools + system_utils +
#      gui_utils + db_tools }}
