# === Ansible SSH and User Settings ===
system_user:
  name: devuser
  create_home: true
  ssh_public_key_path: "{{ ssh_key_dir }}/host_systems.pub"
  groups:
    - video

create_internal_users: false
ssh_key_generate: true

ssh_keys_to_generate:
  - host_systems
  - github
  - gitlab

# === System Behavior Flags ===
allow_reboot: false
install_docker: true

sync_jobs:
  # === Pull app resources from remote systems to control node ===
  - name: Pull app resources
    src: "/opt/app/resources/"
    dest: "./backups/app_resources/{{ inventory_hostname }}/"

  # === Pull database backups from remote systems to control node ===
  - name: Pull DB backups
    src: "/var/backups/db/"
    dest: "./backups/db/{{ inventory_hostname }}/"

  # === Push application files from control node to remote systems ===
  - name: Push app configuration
    src: "./deploy/app_config/"
    dest: "/etc/myapp/config/"
    mode: push  # explicitly override default

# === Source and Destination Paths for File Sync ===
db_backup_source_directory: "{{ sync_source_base }}/db_backups/"
db_backup_destination_directory: "{{ sync_dest_base }}/db/"

app_control_source_directory: "{{ sync_source_base }}/scripts/"
app_control_destination_directory: "{{ sync_dest_base }}/scripts/"

app_files_source_directory: "{{ sync_source_base }}/webapp/"
app_files_destination_directory: "{{ sync_dest_base }}/webapp/"

# === CLI Tool Packages ===
cli_tools:
  - python3-venv
  - fd-find
  - bat
  - jq
  - man-db
  - htop
  - tmux
  - neovim
  - rsync
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - python3-pip
  - virtualenv
  - python3-setuptools
  - ripgrep
  - remmina
  - mariadb-server
  - fuse
  - texlive-full

# === Python Development Packages ===
python_tools:
  - python3-pip
  - virtualenv
  - python3-setuptools
  - python3-dev
  - python3-wheel
  - pipx

# === System Utilities ===
system_utils:
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - fuse
  - net-tools
  - iproute2
  - lsof
  - iotop
  - ncdu
  - sysstat
  - glances
  - rsync
  - acl

# === Graphical Tools and Fonts ===
gui_utils:
  - remmina
  - texlive-full
  - filezilla
  - darktable

# === Local Database Tools ===
db_tools:
  - mariadb-server

# === Combined Package Set for Installation ===
local_system_packages: >-
  {{ cli_tools + gui_utils + db_tools }}
#   {{ cli_tools + python_tools + system_utils +
#      gui_utils + db_tools }}
