group_packages:
  - python3-venv
  - code
  - htop

local_usr: kfcodes

db_backup_source_directory: /data/db/backups/
db_backup_destination_directory: /mnt/devsync/db/

app_control_source_directory: /opt/scripts/
app_control_destination_directory: /mnt/devsync/scripts/

app_files_source_directory: /opt/webapp/
app_files_destination_directory: /mnt/devsync/webapp/

sync_jobs:
  - name: Sync DB backups
    src: "{{ db_backup_source_directory }}"
    dest: "{{ db_backup_destination_directory }}"
    mode: pull

  - name: Sync control scripts
    src: "{{ app_control_source_directory }}"
    dest: "{{ app_control_destination_directory }}"
    mode: pull

  - name: Sync application files
    src: "{{ app_files_source_directory }}"
    dest: "{{ app_files_destination_directory }}"
    mode: pull

